### ISSUE TITLE
i18n navigation

### ISSUE THREAD

**Issue by mayaman** [assemble/grunt-assemble-i18n#56]
Hello,

I am currently building a project in Assemble with a focus on internationalization and would like to use this plug-in, but am having trouble with the set-up process because there is not a lot of documentation here. I am aiming to have my data stored in yml files and then generate multiple pages for each language (currently just english and spanish). I would like to have a button that users can use to translate between languages. My repo is https://github.com/mayaman26/p5js-website 

I would appreciate any assistance/guidance! Thank you.

**Comment by LaurentGoderre** [comment]
To finish your grunt, you are missing this part:

https://github.com/assemble/assemble-middleware-i18n/blob/master/Gruntfile.js#L67-L74

**Comment by LaurentGoderre** [comment]
You could even use a function top generate the list of language instead of hard code them if your list of language is long

**Comment by LaurentGoderre** [comment]
Here is how I would write your task

```javascript
assemble: {
	options:
		flatten: true,
		helpers: ['<%= config.dist %>/assets/js/translation.js'],
		assets: '<%= config.dist %>/assets',
		layout: '<%= config.src %>/templates/layouts/default.hbs',
		data: '<%= config.src %>/data/*.{json,yml}',
		partials: '<%= config.src %>/templates/partials/*.hbs',
		plugins: ['assemble-contrib-permalinks','assemble-contrib-sitemap','assemble-middleware-i18n']
	pages: {
		options: {
			i18n: {
				languages: ["en", "fr", "es"],
				templates: ['<%= config.src %>/templates/pages/*.hbs']
			}
		},
		dest: '<%= config.dist %>',
		src: '!*.*'
	}
}
 ```

**Comment by lmccart** [comment]
Thanks, this is really helpful.  I'm actually picking up on this project from last summer. It's all working great, but I notice that it creates files like `index-en.html` and `index-es.html`. Is it possible to set some option so that it actually creates a separate directory for all the en files and a separate directory for all the es files, etc?

**Comment by lmccart** [comment]
Doh, just saw the permalinks stuff, I'm all set. I think this issue can also be closed, everything asked in this thread has been answered, thank you!

**Comment by ain** [comment]
Yes, @lmccart, we are following the single responsibility concept of modular design, translation engine should not deal with structure, permalinks module is perfectly suited for that.

Glad you worked it out, good luck at your project!
