### ISSUE TITLE
Moving to `grunt-assemble-i18n`

### ISSUE THREAD

**Issue by doowb** [assemble/grunt-assemble-i18n#60]
@LaurentGoderre we'd like to move this code to `grunt-assemble-i18n` and deprecating `assemble-middleware-i18n` on npm.

I noticed there are some outstanding issues and PRs that we can try to resolve before moving. There's also an issue for migrating to `assemble@0.6.0`. We can take a look at the code and see if there's any common code that we might want to extract from this module and create a common module that can be used in both libraries.

If you (or anyone else) have any issues/questions/comments, please leave them here and we can discuss.

**Comment by LaurentGoderre** [comment]
I'd say go for it!

**Comment by doowb** [comment]
Done. There wasn't a need to change any actual code (just some devDependencies that have be renamed too). We can open some other issues to extract code into common libraries and possible make a new middleware/plugin for assemble 0.6.0.

- [x] tagged code snapshot before moving to `grunt-assemble-i18n`
- [x] renamed repo to `grunt-assemble-i18n`
- [x] updated code to use `grunt-assemble` and `grunt-assemble-permalinks` in tests
